"""
git_manager.py
Wraps all Git operations required by the agent: repository initialization,
.gitignore creation, branch configuration, staging, committing and pushing.
Includes a retry/backoff mechanism for transient network failures on push.
"""

from __future__ import annotations

import time
from functools import wraps
from pathlib import Path
from typing import Callable, List, Optional, TypeVar

from git import GitCommandError, InvalidGitRepositoryError, Repo
from git.exc import NoSuchPathError

from config_manager import FolderMapping
from logger_manager import get_logger
from settings import settings

log = get_logger("git_manager")

T = TypeVar("T")

DEFAULT_GITIGNORE = """\
# --- Auto-generated by AI Sync Agent ---
__pycache__/
*.py[cod]
*.egg-info/
.env
.venv/
venv/
node_modules/
dist/
build/
.DS_Store
*.log
.idea/
.vscode/
.pytest_cache/
.mypy_cache/
*.tmp
"""


def retry(max_attempts: Optional[int] = None, backoff: Optional[float] = None):
    """Simple exponential-backoff retry decorator for flaky git/network ops."""

    def decorator(func: Callable[..., T]) -> Callable[..., T]:
        @wraps(func)
        def wrapper(*args, **kwargs) -> T:
            attempts = max_attempts or settings.MAX_GIT_RETRIES
            delay = backoff or settings.GIT_RETRY_BACKOFF
            last_exc: Optional[Exception] = None
            for attempt in range(1, attempts + 1):
                try:
                    return func(*args, **kwargs)
                except (GitCommandError, ConnectionError, TimeoutError) as exc:
                    last_exc = exc
                    log.warning(
                        f"Attempt {attempt}/{attempts} failed for "
                        f"{func.__name__}: {exc}"
                    )
                    if attempt < attempts:
                        time.sleep(delay * attempt)
            assert last_exc is not None
            raise last_exc

        return wrapper

    return decorator


class GitManager:
    """High level Git operations for a single local repository."""

    def __init__(self, folder_path: str):
        self.folder_path = Path(folder_path).expanduser().resolve()
        self.repo: Optional[Repo] = None

    # ------------------------------------------------------------------
    # Repository bootstrap
    # ------------------------------------------------------------------
    def detect_or_init_repo(self, default_branch: str = settings.DEFAULT_BRANCH) -> Repo:
        try:
            self.repo = Repo(self.folder_path)
            log.info(f"Existing Git repository detected at {self.folder_path}")
        except (InvalidGitRepositoryError, NoSuchPathError):
            log.info(f"No Git repository found at {self.folder_path}. Initializing.")
            self.folder_path.mkdir(parents=True, exist_ok=True)
            self.repo = Repo.init(self.folder_path, initial_branch=default_branch)
            self._ensure_git_identity()
            self.ensure_gitignore()
            log.info(f"Initialized new Git repository at {self.folder_path}")
        self.ensure_branch(default_branch)
        return self.repo

    def _ensure_git_identity(self) -> None:
        """Configure a local git user identity if not already set globally."""
        if not self.repo:
            return
        with self.repo.config_writer() as cw:
            if settings.GIT_USER_NAME:
                cw.set_value("user", "name", settings.GIT_USER_NAME)
            if settings.GIT_USER_EMAIL:
                cw.set_value("user", "email", settings.GIT_USER_EMAIL)

    def ensure_gitignore(self) -> None:
        gitignore_path = self.folder_path / ".gitignore"
        if not gitignore_path.exists():
            gitignore_path.write_text(DEFAULT_GITIGNORE, encoding="utf-8")
            log.info(f"Created default .gitignore in {self.folder_path}")

    def ensure_branch(self, branch_name: str) -> None:
        if not self.repo:
            return
        try:
            if self.repo.head.is_valid() and self.repo.active_branch.name == branch_name:
                return
        except (TypeError, ValueError):
            pass  # unborn HEAD (no commits yet) - fine

        existing = [h.name for h in self.repo.heads]
        if branch_name in existing:
            self.repo.git.checkout(branch_name)
        else:
            try:
                self.repo.git.checkout("-b", branch_name)
            except GitCommandError as exc:
                log.debug(f"Branch checkout note: {exc}")

    def ensure_remote(self, remote_url: str, remote_name: str = settings.GIT_REMOTE_NAME) -> None:
        if not self.repo:
            return
        remote_names = [r.name for r in self.repo.remotes]
        if remote_name in remote_names:
            current_url = self.repo.remotes[remote_name].url
            if current_url != remote_url:
                self.repo.remotes[remote_name].set_url(remote_url)
                log.info(f"Updated remote '{remote_name}' URL to {remote_url}")
        else:
            self.repo.create_remote(remote_name, remote_url)
            log.info(f"Added remote '{remote_name}' -> {remote_url}")

    # ------------------------------------------------------------------
    # Status / diff helpers
    # ------------------------------------------------------------------
    def has_changes(self) -> bool:
        if not self.repo:
            return False
        return self.repo.is_dirty(untracked_files=True)

    def get_status_summary(self) -> dict:
        """Returns lists of added/modified/deleted/untracked file paths."""
        if not self.repo:
            return {"added": [], "modified": [], "deleted": [], "untracked": []}

        modified: List[str] = [item.a_path for item in self.repo.index.diff(None) if item.a_path]
        deleted: List[str] = [
            item.a_path for item in self.repo.index.diff(None) if item.deleted_file and item.a_path
        ]
        untracked: List[str] = list(self.repo.untracked_files)

        try:
            staged_added = [
                item.a_path for item in self.repo.index.diff("HEAD") if item.new_file and item.a_path
            ]
        except Exception:
            staged_added = []

        return {
            "added": staged_added,
            "modified": [m for m in modified if m not in deleted],
            "deleted": deleted,
            "untracked": untracked,
        }

    # ------------------------------------------------------------------
    # Core sync operations
    # ------------------------------------------------------------------
    def stage_all(self) -> None:
        if not self.repo:
            return
        self.repo.git.add(A=True)
        log.info(f"Staged all changes in {self.folder_path}")

    def commit(self, message: str) -> Optional[str]:
        if not self.repo:
            return None

        try:
            nothing_staged = not self.repo.git.diff("--cached")
        except GitCommandError:
            nothing_staged = False
        if nothing_staged:
            log.debug("Nothing staged to commit.")
            return None

        try:
            commit_obj = self.repo.index.commit(message)
            commit_log = get_logger("git.commit")
            commit_log.info(f"[{self.folder_path.name}] {message} ({commit_obj.hexsha[:7]})")
            return commit_obj.hexsha
        except Exception as exc:
            log.error(f"Commit failed: {exc}")
            raise

    @retry()
    def push(self, remote_name: str = settings.GIT_REMOTE_NAME, branch: str = settings.DEFAULT_BRANCH) -> bool:
        if not self.repo:
            return False
        push_log = get_logger("git.push")
        try:
            remote = self.repo.remotes[remote_name]
            push_info = remote.push(refspec=f"{branch}:{branch}", set_upstream=True)
            for info in push_info:
                if info.flags & info.ERROR:
                    raise GitCommandError("push", info.summary)
            push_log.info(f"[{self.folder_path.name}] Pushed '{branch}' to '{remote_name}'")
            return True
        except IndexError:
            log.error(f"Remote '{remote_name}' not configured for {self.folder_path}")
            return False
        except GitCommandError as exc:
            push_log.error(f"[{self.folder_path.name}] Push failed: {exc}")
            raise

    # ------------------------------------------------------------------
    # Convenience full-cycle sync
    # ------------------------------------------------------------------
    def sync(self, mapping: FolderMapping, commit_message: str) -> Optional[str]:
        """Stage, commit and (optionally) push. Returns commit sha or None."""
        self.detect_or_init_repo(mapping.branch)
        self.ensure_remote(mapping.remote_url)

        if not self.has_changes():
            log.debug(f"No changes detected in {self.folder_path}; skipping sync.")
            return None

        self.stage_all()
        sha = self.commit(commit_message)
        if sha and mapping.auto_push:
            try:
                self.push(branch=mapping.branch)
            except GitCommandError as exc:
                log.error(f"Push ultimately failed after retries: {exc}")
        return sha
